<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_65e0f418c8b4c',
	'title' => 'Swiper slider',
	'fields' => array(
		array(
			'key' => 'field_65e0f4193a37c',
			'label' => 'Swiper slider',
			'name' => 'block_data',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'sub_fields' => array(
				array(
					'key' => 'field_65e0f43d3a37d',
					'label' => 'Post type',
					'name' => 'post_type',
					'aria-label' => '',
					'type' => 'acfe_post_types',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'field_type' => 'checkbox',
					'default_value' => array(
					),
					'return_format' => 'name',
					'layout' => 'vertical',
					'toggle' => 0,
					'allow_custom' => 0,
					'multiple' => 0,
					'allow_null' => 0,
					'choices' => array(
					),
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'search_placeholder' => '',
					'other_choice' => 0,
				),
				array(
					'key' => 'field_65e0f4613a37e',
					'label' => 'Post per page',
					'name' => 'post_per_page',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/swipper-slider',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1709241732,
));

endif;