<?php
add_action('init', function () {
    register_post_type('food', array(
        'labels' => array(
            'name' => 'Foods',
            'singular_name' => 'Food',
            'menu_name' => 'Foods',
            'all_items' => 'All Foods',
            'edit_item' => 'Edit Food',
            'view_item' => 'View Food',
            'view_items' => 'View Foods',
            'add_new_item' => 'Add New Food',
            'add_new' => 'Add New Food',
            'new_item' => 'New Food',
            'parent_item_colon' => 'Parent Food:',
            'search_items' => 'Search Foods',
            'not_found' => 'No foods found',
            'not_found_in_trash' => 'No foods found in Trash',
            'archives' => 'Food Archives',
            'attributes' => 'Food Attributes',
            'insert_into_item' => 'Insert into food',
            'uploaded_to_this_item' => 'Uploaded to this food',
            'filter_items_list' => 'Filter foods list',
            'filter_by_date' => 'Filter foods by date',
            'items_list_navigation' => 'Foods list navigation',
            'items_list' => 'Foods list',
            'item_published' => 'Food published.',
            'item_published_privately' => 'Food published privately.',
            'item_reverted_to_draft' => 'Food reverted to draft.',
            'item_scheduled' => 'Food scheduled.',
            'item_updated' => 'Food updated.',
            'item_link' => 'Food Link',
            'item_link_description' => 'A link to a food.',
        ),
        'description' => 'Foods post type',
        'public' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-food',
        'supports' => array(
            0 => 'title',
            1 => 'editor',
            2 => 'excerpt',
            3 => 'thumbnail',
        ),
        'taxonomies' => array(
            0 => 'category',
        ),
        'delete_with_user' => false,
    ));
});
